EWMServiceApp:
  name: ewm-service
  stats-service:
    url: http://localhost:9090
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-db
    password: ewm
    username: ewm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: TRACE
          nodeValue: INFO