spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm-db
    password: ewm
    username: ewm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect